services:
  - type: web
    name: gestion-entreprise
    env: dotnet
    buildCommand: dotnet publish -c Release -o ./publish
    startCommand: dotnet publish/mac.dll
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ASPNETCORE_URLS
        value: http://0.0.0.0:$PORT

